Repository cert-manager/csi-driver, pull requests merged in 2020-01, with the labels that each got.

#9 Fix example deployment yaml
  deploy/cert-manager-csi-driver.yaml
  deploy/example/example-app.yaml
Labels: dco-signoff: yes, do-not-merge/release-note-label-needed, lgtm, size/XS

#8 Write CA file is exists in CertificateRequest
  README.md
  pkg/apis/defaults/defaults.go
  pkg/apis/v1alpha1/types.go
  pkg/apis/validation/validation.go
  pkg/certmanager/certmanager.go
  pkg/util/key.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#15 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/M

#14 Add cert-manager link to beginning of README
  README.md
Labels: approved, dco-signoff: yes, lgtm, ok-to-test, release-note-none, size/S

#13 Fix certificate renewal with tests
  Dockerfile
  deploy/cert-manager-csi-driver.yaml
  go.mod
  go.sum
  pkg/certmanager/certmanager.go
  pkg/driver/nodeserver.go
  pkg/renew/renew.go
  pkg/renew/renew_test.go
  pkg/util/csr.go
  pkg/util/csr_test.go
  test/e2e/environment/environment.go
  test/e2e/framework/helper/certificaterequest.go
  test/e2e/framework/helper/host.go
  test/e2e/framework/helper/pod.go
  test/e2e/framework/testenv.go
  test/e2e/suite/cases/renew.go
  test/e2e/suite/cases/stress.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL
