Repository cert-manager/csi-driver, pull requests merged in 2021-09, with the labels that each got.

#46 Unit tests
  README.md
  docs/design/20190914.certificaterenewal.md
  go.mod
  pkg/apis/defaults/defaults.go
  pkg/apis/v1alpha1/types.go
  pkg/apis/validation/validation.go
  pkg/apis/validation/validation_test.go
  pkg/filestore/writer.go
  pkg/filestore/writer_test.go
  pkg/keygen/keygen.go
  pkg/requestgen/generator.go
  test/e2e/framework/helper/pod.go
  test/e2e/framework/helper/spec.go
Labels: dco-signoff: yes, lgtm, approved, size/XL, release-note-none

#47 Boilerplate
  Dockerfile
  Makefile
  cmd/app/options/options.go
  cmd/app/start.go
  cmd/main.go
  hack/boilerplate/BUILD.bazel
  hack/boilerplate/boilerplate.Dockerfile.txt
  hack/boilerplate/boilerplate.Makefile.txt
  hack/boilerplate/boilerplate.go.txt
  hack/boilerplate/boilerplate.py
  hack/boilerplate/boilerplate.py.txt
  hack/boilerplate/boilerplate.sh.txt
  hack/boilerplate/boilerplate_test.py
  hack/verify-boilerplate.sh
  hack/verify_boilerplate.py
  pkg/apis/defaults/defaults.go
  pkg/apis/doc.go
  pkg/apis/v1alpha1/types.go
  pkg/apis/validation/validation.go
  pkg/apis/validation/validation_test.go
  pkg/filestore/writer.go
  pkg/filestore/writer_test.go
  pkg/keygen/keygen.go
  pkg/requestgen/generator.go
  test/e2e/environment/environment.go
  test/e2e/framework/cleanup.go
  test/e2e/framework/config/config.go
  test/e2e/framework/config/ginkgo.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/certificaterequest.go
  test/e2e/framework/helper/helper.go
  test/e2e/framework/helper/kubectl.go
  test/e2e/framework/helper/pod.go
  test/e2e/framework/log/log.go
  test/e2e/framework/testdata/testdata.go
  test/e2e/framework/testenv.go
  test/e2e/framework/util.go
  test/e2e/framework/util/util.go
  test/e2e/suite/cases/renew.go
  test/e2e/suite/cases/stress.go
  test/e2e/suite/cases/usages.go
  test/e2e/suite/cases/util.go
  test/e2e/suite/suite.go
  test/e2e/suite/suite_test.go
  test/e2e/util/csr.go
  test/e2e/util/csr_test.go
  test/e2e/util/metadata.go
  test/e2e/util/parse.go
  test/e2e/util/strings.go
  test/run.sh
Labels: dco-signoff: yes, lgtm, approved, size/XL, release-note-none

#48 Security.md
  SECURITY.md
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#49 Repo cert manager csi
  cmd/app/start.go
  cmd/main.go
  go.mod
  pkg/apis/defaults/defaults.go
  pkg/apis/validation/validation.go
  pkg/apis/validation/validation_test.go
  pkg/filestore/writer.go
  pkg/keygen/keygen.go
  pkg/requestgen/generator.go
  test/e2e/framework/config/config.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/certificaterequest.go
  test/e2e/framework/helper/helper.go
  test/e2e/framework/helper/kubectl.go
  test/e2e/framework/helper/pod.go
  test/e2e/framework/util.go
  test/e2e/suite/cases/renew.go
  test/e2e/suite/cases/stress.go
  test/e2e/suite/cases/usages.go
  test/e2e/suite/suite.go
  test/e2e/suite/suite_test.go
  test/e2e/util/csr.go
  test/e2e/util/metadata.go
Labels: dco-signoff: yes, lgtm, approved, size/M, release-note-none

#50 Cmd options
  cmd/app/app.go
  cmd/app/options/options.go
  cmd/app/start.go
  cmd/main.go
  go.mod
  go.sum
Labels: dco-signoff: yes, size/L, lgtm, approved, release-note-none

#51 Cmd ctx cancel
  cmd/app/app.go
Labels: dco-signoff: yes, size/XS, lgtm, approved, release-note-none

#52 Helm chart
  Makefile
  README.md
  deploy/charts/csi-driver/Chart.yaml
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/templates/_helpers.tpl
  deploy/charts/csi-driver/templates/clusterrole.yaml
  deploy/charts/csi-driver/templates/clusterrolebinding.yaml
  deploy/charts/csi-driver/templates/csidriver.yaml
  deploy/charts/csi-driver/templates/daemonset.yaml
  deploy/charts/csi-driver/templates/serviceaccount.yaml
  deploy/charts/csi-driver/values.yaml
  deploy/example/example-app.yaml
  test/run.sh
Labels: dco-signoff: yes, size/L, lgtm, approved, release-note

#53 Fs group
  Makefile
  README.md
  cmd/app/app.go
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/templates/_helpers.tpl
  deploy/charts/csi-driver/templates/clusterrole.yaml
  deploy/charts/csi-driver/templates/clusterrolebinding.yaml
  deploy/charts/csi-driver/templates/csidriver.yaml
  deploy/charts/csi-driver/templates/daemonset.yaml
  deploy/charts/csi-driver/templates/serviceaccount.yaml
  pkg/apis/v1alpha1/types.go
  test/e2e/framework/testenv.go
  test/e2e/suite/cases/fsgroup.go
Labels: dco-signoff: yes, size/L, lgtm, approved, release-note-none

#56 Update csi-lib to v0.1.0
  go.mod
  go.sum
Labels: dco-signoff: yes, size/XS, lgtm, approved

#57 Actually return wrapped error, fix docstring lint
  cmd/app/app.go
Labels: dco-signoff: yes, size/XS, lgtm, approved

#58 Ensure all names use cert-manager-csi-driver
  .gitignore
  Dockerfile
  cmd/app/app.go
  cmd/main.go
  test/e2e/suite/suite_test.go
  test/run.sh
Labels: dco-signoff: yes, size/S, lgtm, approved

#59 Bump storage API version v1beta1 -> v1
  deploy/charts/csi-driver/templates/csidriver.yaml
  deploy/example/example-app.yaml
  test/run.sh
Labels: dco-signoff: yes, size/S, lgtm, approved

#61 Use k8s.gcr.io repo for csi-node-driver-registrar
  deploy/charts/csi-driver/templates/daemonset.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#60 Adds support for multi-arch images, bumps version to v0.1.1
  Dockerfile
  Makefile
  cmd/app/app.go
  deploy/charts/csi-driver/Chart.yaml
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/values.yaml
  test/run.sh
Labels: dco-signoff: yes, lgtm, approved, size/M

#62 Explain incompatibility with self signed issuers
  README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved

#64 Updates helm chart to v0.1.2
  deploy/charts/csi-driver/Chart.yaml
  deploy/charts/csi-driver/README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved
