Repository cert-manager/csi-driver, pull requests merged in 2022-08, with the labels that each got.

#103 PKCS12 Support
  deploy/example/example-app.yaml
  go.mod
  go.sum
  pkg/apis/defaults/defaults.go
  pkg/apis/defaults/defaults_test.go
  pkg/apis/v1alpha1/types.go
  pkg/apis/validation/validation.go
  pkg/apis/validation/validation_test.go
  pkg/filestore/writer.go
  pkg/filestore/writer_test.go
  pkg/keygen/keygen.go
  pkg/keystore/pkcs12/pkcs12.go
  pkg/keystore/pkcs12/pkcs12_test.go
  test/e2e/framework/helper/pod.go
  test/e2e/suite/cases/fsgroup.go
  test/e2e/suite/cases/keyencoding.go
  test/e2e/suite/cases/pkcs12.go
  test/e2e/suite/cases/renew.go
  test/e2e/suite/cases/stress.go
  test/e2e/suite/cases/usages.go
  test/e2e/suite/cases/util.go
  test/e2e/suite/cases/variables.go
  test/e2e/util/metadata.go
  test/unit/cert.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#97 Move kind and helm to hack tools
  Makefile
  go.mod
  go.sum
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  test/run.sh
Labels: dco-signoff: yes, lgtm, approved, size/XL

#104 Introduce a new filename validation function
  pkg/apis/validation/validation.go
  pkg/apis/validation/validation_test.go
  pkg/filestore/writer_test.go
Labels: dco-signoff: yes, size/L, lgtm, approved

#107 Upgrade go to v1.19
  Dockerfile
  go.mod
  hack/tools/go.mod
Labels: dco-signoff: yes, size/XS, lgtm, approved

#98 Upgrade Kubernetes e2e test version to v1.24.1
  test/run.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#108 Updates release to v0.4.0, ready for release
  Makefile
  deploy/charts/csi-driver/Chart.yaml
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/values.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#110 Remove life cycle hook from Daemonset
  deploy/charts/csi-driver/Chart.yaml
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/templates/daemonset.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#113 Add support for imagePullSecrets. Fixes #112
  deploy/charts/csi-driver/Chart.yaml
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/templates/daemonset.yaml
  deploy/charts/csi-driver/templates/serviceaccount.yaml
  deploy/charts/csi-driver/values.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved, needs-ok-to-test

#115 Remove extra } from the sample uri-san
  deploy/example/example-app.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved, ok-to-test
