Repository cert-manager/csi-driver, pull requests merged in 2022-11, with the labels that each got.

#120 Add support for non-standard kubelet root directory
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/templates/daemonset.yaml
  deploy/charts/csi-driver/values.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved, ok-to-test

#122 Updates alpine in Dockerfile to 3.16.2
  Dockerfile
Labels: dco-signoff: yes, size/XS, lgtm, approved

#121 Updates go modules, including csi-lib to v0.4.0
  go.mod
  go.sum
  test/e2e/framework/framework.go
  test/e2e/framework/log/log.go
  test/e2e/framework/util.go
  test/e2e/suite/cases/fsgroup.go
  test/e2e/suite/cases/keyencoding.go
  test/e2e/suite/cases/pkcs12.go
  test/e2e/suite/cases/renew.go
  test/e2e/suite/cases/stress.go
  test/e2e/suite/cases/usages.go
  test/e2e/suite/cases/variables.go
  test/e2e/suite/suite.go
  test/e2e/suite/suite_test.go
Labels: dco-signoff: yes, lgtm, approved, size/XL

#114 For attributes that are lists, trim space for each entry to improve UX.
  deploy/example/example-app.yaml
  pkg/requestgen/generator.go
  pkg/requestgen/generator_test.go
  test/e2e/suite/cases/variables.go
Labels: dco-signoff: yes, lgtm, approved, size/M
