Repository cert-manager/csi-driver, pull requests merged in 2022-05, with the labels that each got.

#91 Remove disable-auto-renew from example Deployment
  deploy/example/example-app.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#85 Update cert-manager:v1.8.0 in test runner
  test/run.sh
Labels: dco-signoff: yes, size/XS, lgtm, approved

#87 Bumps alpine version `v3.14` -> `v3.15`
  Dockerfile
Labels: dco-signoff: yes, size/XS, lgtm, approved

#84 Updates reference in SECURITY.md to point to `jetstack/cert-manager` -> `cert-manager/cert-manager`
  SECURITY.md
Labels: dco-signoff: yes, size/XS, lgtm, approved

#89 Bumps bump-csi-node-driver-registrar to `v2.5.0`, Bumps livenessprobe to `v2.6.0`
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/values.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#83 Bump cert-manager/csi-lib to v0.2.2
  cmd/app/app.go
  cmd/app/options/options.go
  go.mod
  go.sum
  pkg/apis/defaults/defaults.go
  pkg/apis/validation/validation.go
  pkg/apis/validation/validation_test.go
  pkg/filestore/writer.go
  pkg/keygen/keygen.go
  pkg/requestgen/generator.go
  pkg/requestgen/generator_test.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/certificaterequest.go
  test/e2e/framework/helper/helper.go
  test/e2e/framework/helper/pod.go
  test/e2e/framework/testenv.go
  test/e2e/suite/cases/stress.go
  test/e2e/suite/cases/variables.go
  test/e2e/util/csr.go
  test/e2e/util/metadata.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#90 Sets csi-driver version to v0.3.0
  Makefile
  cmd/app/app.go
  deploy/charts/csi-driver/Chart.yaml
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/values.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#93 Update to smaller logo with correct size
  README.md
Labels: dco-signoff: yes, size/XS, lgtm, approved
