Repository cert-manager/csi-driver, pull requests merged in 2024-03, with the labels that each got.

#220 Use CSIDriver v1 unconditionally
  deploy/charts/csi-driver/templates/csidriver.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#212 Pass non-driver volumeAttributes to the created CertificateRequest
  pkg/requestgen/generator.go
  pkg/requestgen/generator_test.go
  test/e2e/suite/cases/annotations.go
Labels: dco-signoff: yes, size/L, lgtm, approved, ok-to-test

#223 Add default container annotation to daemonset
  deploy/charts/csi-driver/templates/daemonset.yaml
Labels: dco-signoff: yes, size/XS, lgtm, approved

#224 Add initial documentation of release process
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/M

#226 Add go module and replace oci-image with oci-build and oci-publish
  .github/workflows/govulncheck.yaml
  .golangci.yaml
  cmd/app/options/options.go
  klone.yaml
  make/00_mod.mk
  make/_shared/go/.golangci.override.yaml
  make/_shared/go/01_mod.mk
  make/_shared/go/README.md
  make/_shared/go/base/.github/workflows/govulncheck.yaml
  make/_shared/oci-build/00_mod.mk
  make/_shared/oci-build/01_mod.mk
  make/_shared/oci-build/image_tool/go.mod
  make/_shared/oci-build/image_tool/go.sum
  make/_shared/oci-build/image_tool/main.go
  make/_shared/oci-image/01_mod.mk
  make/_shared/oci-publish/01_mod.mk
  pkg/requestgen/generator_test.go
  test/e2e/environment/environment.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/certificaterequest.go
  test/e2e/framework/util.go
  test/e2e/suite/cases/annotations.go
  test/e2e/suite/cases/fsgroup.go
  test/e2e/suite/cases/keyencoding.go
  test/e2e/suite/cases/pkcs12.go
  test/e2e/suite/cases/renew.go
  test/e2e/suite/cases/stress.go
  test/e2e/suite/cases/usages.go
  test/e2e/suite/cases/util.go
  test/e2e/suite/cases/variables.go
  test/e2e/suite/suite.go
  test/e2e/util/metadata.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#227 Fix linters
  .golangci.yaml
  cmd/app/options/options.go
  pkg/apis/defaults/defaults.go
  pkg/apis/validation/validation_test.go
  pkg/keystore/pkcs12/pkcs12.go
  test/e2e/framework/framework.go
  test/e2e/framework/helper/certificaterequest.go
  test/e2e/framework/helper/pod.go
  test/e2e/framework/log/log.go
  test/e2e/framework/testenv.go
  test/e2e/suite/cases/annotations.go
  test/e2e/suite/cases/fsgroup.go
  test/e2e/suite/cases/keyencoding.go
  test/e2e/suite/cases/pkcs12.go
  test/e2e/suite/cases/renew.go
  test/e2e/suite/cases/stress.go
  test/e2e/suite/cases/usages.go
  test/e2e/suite/cases/util.go
  test/e2e/suite/cases/variables.go
  test/e2e/util/metadata.go
Labels: dco-signoff: yes, size/L, lgtm, approved
