Repository cert-manager/csi-driver, pull requests merged in 2024-01, with the labels that each got.

#177 Upgrade repository-base module
  .github/workflows/make-self-upgrade.yaml
  Makefile
  klone.yaml
  make/_shared/repository-base/base/.github/workflows/make-self-upgrade.yaml
  make/_shared/repository-base/base/Makefile
Labels: dco-signoff: yes, size/XS, lgtm, approved

#179 Upgrade 'csi-node-driver-registrar' and 'livenessprobe'
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/values.yaml
Labels: dco-signoff: yes, size/S, lgtm, approved

#183 Upgrade oci-image module
  klone.yaml
  make/00_mod.mk
  make/_shared/oci-image/01_mod.mk
  make/_shared/tools/00_mod.mk
Labels: dco-signoff: yes, lgtm, approved, size/M

#184 Add version info to binary at compile time
  cmd/app/app.go
  internal/version/version.go
Labels: dco-signoff: yes, lgtm, approved, size/M

#193 MMcL-values-edit
  deploy/charts/csi-driver/README.md
  deploy/charts/csi-driver/values.yaml
Labels: dco-signoff: yes, lgtm, approved, size/M, ok-to-test
